[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["cd frontend && npm install", "cd backend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build && mkdir -p ../backend/frontend-dist && cp -r dist/* ../backend/frontend-dist/", "cd backend && npx prisma generate && npx tsc"]

[start]
cmd = "cd backend && npm run start"
