[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npm run build && npx prisma db push && npx prisma db seed"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
